# --- !Ups

CREATE TABLE box_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  box_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_box FOREIGN KEY (box_id) REFERENCES boxes(id) ON DELETE CASCADE,
  CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
);


# --- !Downs

DROP TABLE IF EXISTS box_items;